############################################################
# Dockerfile to build jlib for gcc:10
# Based on Ubuntu Image
############################################################

# Set the base image to use to gcc:10
FROM ubuntu:18.04

# Set the file maintainer
MAINTAINER Joey Yandle

RUN apt update
RUN apt upgrade -y
RUN apt install -y build-essential
RUN apt install -y wget pkg-config libsigc++-2.0-dev libglibmm-2.4-dev libgpgme11-dev libx11-dev freeglut3-dev libmagick++-dev libjson-c-dev gdb vim
RUN apt install -y libssl-dev
RUN apt install -y automake autoconf autoconf-archive

RUN wget https://github.com/jedisct1/libsodium/releases/download/1.0.18-RELEASE/libsodium-1.0.18.tar.gz
RUN tar xvzf libsodium-1.0.18.tar.gz
RUN cd libsodium-1.0.18 && ./configure --enable-opt --enable-shared=no --with-pic --prefix=/usr && make -j16 && make install

COPY Makefile.am /root/src/jlib/Makefile.am
COPY configure.ac /root/src/jlib/configure.ac
COPY AUTHORS /root/src/jlib/
COPY ChangeLog /root/src/jlib/
COPY NEWS /root/src/jlib/
COPY README /root/src/jlib/
COPY jlib/ /root/src/jlib/jlib/
COPY tests/ /root/src/jlib/tests/

WORKDIR /root/src/jlib

RUN autoreconf -i

RUN mkdir /root/src/jlib/build
WORKDIR /root/src/jlib/build

RUN ../configure
RUN make -j8

ENTRYPOINT /bin/bash
