#include <iostream>

#include <jlib/util/Headers.hh>

int main(int argc, char** argv) {

    std::string raw = "Return-Path: <atinnell@meridiansite.com>\n"
      "Delivered-To: jwy@bubblehouse.divisionbyzero.com\n"
      "Received: from 216.105.128.24 (mail.acsinc.net [216.105.128.24])\n"
      "by bubblehouse.divisionbyzero.com (Postfix) with SMTP id 948FB5BD87\n"
      "for <jwy@divisionbyzero.com>; Mon,  3 Dec 2001 15:01:45 -0800 (PST)\n"
      "Received: from pc325 ([208.216.230.245]) by 216.105.128.24 ; Mon, 03 Dec 2001 22:05:36 -0100\n"
      "Message-ID: <006301c17c35$d4039500$3800260a@SBPhillips.com>\n"
      "From: \"Angie Tinnell\" <atinnell@meridiansite.com>\n"
      "To: \"Wood Chuck\" <chuck.wood@volvo.com>, <WILLSPW@aol.com>,\n"
      "\"Willie Martin\" <wmartin@gnl.com>, \"WEDP\" <WEDP@carolina.rr.com>,\n"
      "<wanda@wbcraig.com>, \"Victor Eng\" <veng@STOPANDSHOP.COM>,\n"
      "\"Upchurch Pat\" <pat.upchurch@volvo.com>, <Twinelec@aol.com>,\n"
      "\"Tony Gentry\" <tgentry@waukbearing.com>, <Tom_Miller@mannington.com>,\n"
      "<TLCrowder25015@aol.com>, <tim.courtney.texas@nolato.com>,\n"
      "\"Tim Chappell\" <Tim.Chappell@na.clariant.com>,\n"
      "\"THOMAS LINDEMUTH\" <tflindemuth@hotmail.com>,\n"
      "\"The Masons\" <tejas@perigee.net>,\n"
      "\"Teresa Medlin\" <teresamedlin@aholdusa.com>,\n"
      "\"Susan Newby\" <SusanNewby@kayser-roth.com>,\n"
      "\"Steven Shiflet\" <sshiflet@ekachem.com>,\n"
      "<Steve.Freeman@IndSys.ge.com>, <Stephen.Tinnell@coachusa.com>,\n"
      "\"Stephanie Dawkins\" <parts3.dawkins@memo.volvo.com>,\n"
      "<SRick1944@aol.com>, <SReedOSU@cs.com>, <sid.stephens@syngenta.com>,\n"
      "\"Sherry Kennedy\" <skennedy@gnl.com>,\n"
      "\"Shellie Lambert\" <slambert@GiantofMaryland.com>,\n"
      "\"Shannon Kisner\" <skisner@balinet.com>,\n"
      "\"Scott Foisy\" <sf@ix.netcom.com>, \"Scott Foisy\" <sfoisy@dbm.com>,\n"
      "\"Sarah Newby\" <SarahNewby@kayser-roth.com>,\n"
      "\"SAMUEL PETROS\" <sepl@msn.com>, <Samotlagh@aol.com>,\n"
      "\"Sam White\" <swhitejr@bellsouth.net>, <russ.cappello@ohr.gatech.edu>,\n"
      "\"Ron Grant\" <rgrant@meridiansite.com>,\n"
      "\"Ron Grant\" <rgrant@sbphillips.com>, <ROITEAM@aol.com>,\n"
      "\"Robert Montgomery\" <rmontgom@cambridgeport.com>,\n"
      "\"Robert Hauser\" <rhauser@searchmeister.com>,\n"
      "\"Robert  Rankin\" <rankin2@worldnet.att.net>,\n"
      "\"Rich Sartini\" <rich.sartini@us.michelin.com>,\n"
      "\"Rhonda York\" <RYork321@aol.com>,\n"
      "\"Rhonda York\" <ryork@meridiansite.com>,\n"
      "\"Rhonda Patterson\" <rpatterson@dbm.com>,\n"
      "\"Resumes\" <resumes@meridiansite.com>,\n"
      "\"Rebecca Manning\" <rebeccamanning30@hotmail.com>,\n"
      "\"Randy Sternadel\" <sternarh@tisd.net>, <RagTop45@aol.com>,\n"
      "\"Rae Mackall\" <raemackall@kayser-roth.com>,\n"
      "<pycp@greenville.infi.net>, <PMan633000@aol.com>,\n"
      "\"Piece Sawyer\" <sawyer@vnet.net>,\n"
      "\"Peggy Gillispie\" <pgillispie@gnl.com>,\n"
      "\"paul declue\" <pdeclue@meridiansite.com>,\n"
      "\"Patt Slavin\" <pslavin@meridiansite.com>,\n"
      "\"Patricia Woods\" <LIFESCAPES@comporium.net>,\n"
      "\"Patricia Antonitis Woods\" <pwoods@meridiansite.com>,\n"
      "\"Pat Knight\" <patk@rightflorida.com>,\n"
      "\"OfishialBusiness\" <OfishialBusiness@home.com>,\n"
      "\"niter\" <niter@asap-com.com>, \"nicky kennedy\" <nsken@rtmc.net>,\n"
      "\"Nancy O'Neal\" <Nancy.ONeal@Comporium.Com>,\n"
      "\"MSNBC_NEWS_East_Coast@msnbc.exactis.com\" <1842339141.1.244631733@vopt.esm.tm0.com>,\n"
      "<mleesaylor@aol.com>, \"Mitzi Helton\" <mhelton@sbphillips.com>,\n"
      "\"Mitchiner, Dotty\" <DMitchiner@Carolina.CMAC.com>,\n"
      "<MimiJ4242@aol.com>, <milliel@rutherford.k12.nc.us>,\n"
      "<MikeTownshend@aol.com>, \"Mike Hoyle\" <hoylem@shelby.net>,\n"
      "\"Mike Carico\" <carico@northstate.net>,\n"
      "\"Mike Brock\" <mike.brock@cingular.com>,\n"
      "\"Microsoft Office Support\" <v-1bfars@mssupport.microsoft.com>,\n"
      "\"Michael Williams\" <derrwill@bellsouth.net>,\n"
      "\"Michael Joyce\" <mjoyce2@triad.rr.com>,\n"
      "\"Michael Jett\" <mjett@home.com>,\n"
      "\"meridiansite.com\" <jmccarthy@meridiansite.com>, <MEMONTES@aol.com>,\n"
      "<mattiagoddard@hotmail.com>, \"MaryJo Hetrick\" <maryjo@theramp.net>,\n"
      "\"Mary Ann-N516471 Price\" <Mary-Ann.Price@us.michelin.com>,\n"
      "\"Martha Harbin\" <mharbin@sbphillips.com>,\n"
      "\"Martha Brown\" <mbrown@gnl.com>,\n"
      "\"Mark Richardson\" <mrichardson@meridiansite.com>,\n"
      "\"Mark Richardson\" <mrichardson@sbphillips.com>,\n"
      "\"Mark\" <comfortmbnc@northstate.net>, <lynn.lail@ah.Novartis.com>,\n"
      "\"Lynn Martin\" <lmartin@sbphillips.com>, <loridvorak@bellsouth.net>,\n"
      "<LMULL50@aol.com>, \"Linda Wilson\" <lwilson@meridiansite.com>,\n"
      "\"Libba Haggerson\" <william.libba@mindspring.com>,\n"
      "\"Libba\" <Elizabeth.M.Haggerson@bankofamerica.com>,\n"
      "\"Les & Lani Moretz\" <doublel@loclnet.com>, <LEMIII33@aol.com>,\n"
      "\"Lawrence Hilliard\" <lhilliar@STOPANDSHOP.COM>,\n"
      "\"Larry McAdams/HR/HQ/KEMET/US\" <LarryMcAdams@kemet.com>,\n"
      "\"Larry Earwood\" <up01393@deere.com>,\n"
      "\"Lainyvin\" <Lainyvin@email.msn.com>, \"Kimps, Barb\" <bkimps@kcc.com>,\n"
      "\"Kevin Williamson\" <Kevin_Williamson@averydennison.com>,\n"
      "\"Kelly Causey\" <kcausey@sbphillips.com>, <KelJHobbs@aol.com>,\n"
      "<KDAILC@aol.com>, \"Kathy Johnston\" <kjohnston@sbphillips.com>,\n"
      "\"Karmen Briley\" <Karmen.Briley@cingular.com>,\n"
      "\"Karl Schweitzer\" <kschweitzer@STOPANDSHOP.COM>,\n"
      "<karen.johnson@syngenta.com>,\n"
      "\"Juergen Kortberg\" <jkortberg@searchmeister.com>,\n"
      "\"Joyner, Matthew\" <Matthew_Joyner@yorkshireamericas.com>,\n"
      "<Jonesje57@aol.com>, \"Jonathan Gruber\" <agruber@carolina.rr.com>,\n"
      "\"Johnnie Buff\" <jbuff@gnl.com>, <john.stone@syngenta.com>,\n"
      "\"John Yandle\" <jyandle@regacc.com>,\n"
      "\"John Kahler\" <jkahler@STOPANDSHOP.COM>,\n"
      "\"John Cooper\" <jcooper@GiantOfMaryland.com>,\n"
      "\"John Campbell\" <John_Campbell@labcorp.com>,\n"
      "<joey.yavanhxay@syngenta.com>, \"Joe Yandle\" <jwy@divisionbyzero.com>,\n"
      "<joanne.hodge@syngenta.com>, \"Joan Haith\" <jhaith@triad.rr.com>,\n"
      "<jmc@frodo.net>, <Jlgunn@aol.com>,\n"
      "\"Jim Skaats\" <jskaats@careerlearningsystems.com>,\n"
      "\"Jim Boyd\" <Jim.Boyd@dayzim.com>,\n"
      "\"Jim Argento\" <jimang72@netzero.net>, <JFD615@aol.com>,\n"
      "\"Jeff Hopkins\" <jhopkins@esurfsolutions.com>, <Jeancls@aol.com>,\n"
      "<JDM1965@aol.com>, \"Janice Barry\" <jbarry@sbphillips.com>,\n"
      "\"Janer, Danielle\" <djaner01@sprintspectrum.com>,\n"
      "\"Jane McCarthy\" <janemcc@fast.net>, \"Jane Ko\" <jko@sbphillips.com>,\n"
      "<james.paterson@volvo.com>,\n"
      "\"James Paterson\" <VTNA.JAMESP@MEMO.VOLVO.COM>,\n"
      "\"James Bronson\" <jbronson@gnl.com>,\n"
      "\"Jacqueline Mooneyhan\" <JMooneyhan@Carolina.CMAC.com>,\n"
      "<J52ODONNELL@aol.com>, \"Ivory Medina\" <inmedina@hotmail.com>,\n"
      "\"Huffman, Brian\" <BHuffm01@sprintspectrum.com>,\n"
      "\"Howard, Byron\" <howardb1@odc.edu>, <HJ755@aol.com>,\n"
      "<HintzeGene@aol.com>, <helen.biggerstaff@cp.Novartis.com>,\n"
      "\"Heidi Hauser\" <hhauser@meridiansite.com>,\n"
      "\"Harriette Wood/HR/HQ/KEMET/US\" <HarrietteWood@kemet.com>,\n"
      "<Gwlea@aol.com>, \"Gretchen M Swanson\" <gswanson@STOPANDSHOP.COM>,\n"
      "\"Greg Turner\" <gturner@expressa.net>,\n"
      "\"Green Wendy\" <wendy.green@volvo.com>,\n"
      "\"gnjcurry\" <gnjcurry@carolina.rr.com>, <GKennedydoc@aol.com>,\n"
      "\"Fred Yarbrough\" <fyarbrough@gnl.com>,\n"
      "\"Fred Merrin\" <fritzm@linkline.com>,\n"
      "\"Frank Clarkson\" <frankc60@mediaone.net>, <FCoots@aol.com>,\n"
      "<Ewok1309@aol.com>, <etinnell@hovac.com>,\n"
      "\"Essex, Jesse\" <Jesse.Essex@SFX.com>, <esmith@contecinc.com>,\n"
      "\"Emily-N505935 Edwards\" <Emily.Edwards@us.michelin.com>,\n"
      "\"Elizabeth O'Reilly\" <eoreilly@stopandshop.com>,\n"
      "<elaine.mitchell@syngenta.com>,\n"
      "\"Earwood Larry\" <EarwoodLarry@JohnDeere.com>,\n"
      "\"Doug Newton\" <doug.newton@ryobitools.com>, <DorrellLawton@aol.com>,\n"
      "\"Don Hill\" <dhill@meridiansite.com>,\n"
      "\"Don E Bringle\" <d-bringle@juno.com>, <Dick.Price@sonoco.com>,\n"
      "\"Dennis Cornetta\" <dcornetta@meridiansite.com>,\n"
      "\"Deleise Lindsay\" <dlindsay@dbm.com>,\n"
      "\"Dean Matthews\" <dmatth01@sprintspectrum.com>,\n"
      "\"Dawkins Stephanie\" <stephanie.dawkins@volvo.com>,\n"
      "\"David Shirlen\" <david.shirlen@nationaltextiles.com>,\n"
      "\"David Sellman\" <dsellman@northstate.net>,\n"
      "\"David Carr\" <dcarr@gmi.net>, <DaveAndGulshan@pcprosinc.net>,\n"
      "<Darnell.Sharpless@nationaltextiles.com>,\n"
      "\"Daniel Grieco\" <dangrieco@hotmail.com>, <DABrannon@aol.com>,\n"
      "<cziehm@meridiansite.com>, <cysdsimms@att.net>,\n"
      "\"CS COOKE\" <CSCOOKE@CHARTER.NET>,\n"
      "\"Crawford Chavous\" <cchavous@sbphillips.com>,\n"
      "\"Clint Butler\" <cbutler@iq-interactive.com>,\n"
      "\"Chuck Kilbride\" <ckilbride@dbm.com>,\n"
      "\"Chuck Fontaine\" <cfontaine@STOPANDSHOP.COM>,\n"
      "\"Chris Clear\" <csclear@triad.rr.com>,\n"
      "\"Cheri Weidman\" <cweidman@sbphillips.com>,\n"
      "\"Charlie Luper\" <txluper@home.com>,\n"
      "\"Charlie Forbes\" <CForbes@gnl.com>,\n"
      "\"Charlie Donohoe\" <cdonohoe@dbm.com>,\n"
      "\"Cecelia Hardee\" <CHARDEE@tritonpcs.com>, <c-deals@dnai.com>,\n"
      "\"Cathy Harris\" <caharris@carolina.rr.com>,\n"
      "\"Carl Vincent\" <carl.vincent@springs.com>,\n"
      "\"Cam Donovan\" <cdonovan@sbphillips.com>,\n"
      "\"Bruce Storer\" <Bruce_Storer@labcorp.com>,\n"
      "\"Bruce McNeill\" <bmcneill@gnl.com>,\n"
      "\"Bruce Goff\" <bgoff@STOPANDSHOP.COM>,\n"
      "\"Brown, Philip L\" <Philip.L.Brown@rolls-royce.com>,\n"
      "<brittsrp@att.net>, <Brian.Baker@coachusa.com>,\n"
      "\"Brent deMoville\" <demoville_brent@allergan.com>,\n"
      "\"Branden, Laura\" <BRANDENL@mail.ecu.edu>,\n"
      "\"Brad Hughes\" <bhughes@apacheproducts.com>,\n"
      "\"Brad\" <forrest@asheboro.com>, \"Bobby Lamb\" <lambr@bellsouth.net>,\n"
      "<Bob.Russ@nationaltextiles.com>,\n"
      "\"Bob Vanpeeren\" <rvanpeeren@hotmail.com>,\n"
      "\"Bob Rouleau\" <brouleau@STOPANDSHOP.COM>,\n"
      "\"Bob Edwards\" <bedwards@gnl.com>, <BlantonP@aol.com>,\n"
      "<Bk4502@aol.com>, <birder@nr.infi.net>,\n"
      "\"Bill Robinson\" <brobinson@meridiansite.com>,\n"
      "\"Bill Robinson\" <brobinson@sbphillips.com>,\n"
      "\"Bill Conway\" <bill.conway@ryobitools.com>,\n"
      "\"Bill Bailey\" <baileywh@bp.com>,\n"
      "\"Beauchamp, Tracee\" <tbeaucha@dcri.net>,\n"
      "\"Barry Ray\" <bray@brettpr.com>,\n"
      "\"Barefoot Tracie\" <tracie.barefoot@volvo.com>,\n"
      "<Barbara_Winkler@bba-nonwovens.com>,\n"
      "\"Barbara Taylor\" <btaylor@meridiansite.com>,\n"
      "\"Barbara J Taylor\" <salem77@juno.com>, \"ARN VOGT\" <ARNVOGT@msn.com>,\n"
      "<Anita.Caldwell@usa.contiteves.com>,\n"
      "\"Angela Crain\" <acrain@bionetrix.com>,\n"
      "\"Angela Campbell\" <Angelac@Roystonllc.com>,\n"
      "\"Andy Hall\" <andyhall95@hotmail.com>,\n"
      "\"Amy Landis\" <alandis@streetconstruction.com>, <AMTM2@aol.com>,\n"
      "<alanh@alltel.net>, <Aguileromig@aol.com>\n"
      "Subject: Email Virus\n"
      "Date: Mon, 3 Dec 2001 15:02:47 -0500\n"
      "MIME-Version: 1.0\n"
      "Content-Type: multipart/alternative;\n"
      "boundary=\"----=_NextPart_000_005E_01C17C0B.91F7B8A0\"\n"
      "\n"
      "\n";

    jlib::util::Headers headers(raw);
    return 0;
}
