Document: jlib
Title: Debian jlib Manual
Author: <insert document author here>
Abstract: This manual describes what jlib is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/jlib/jlib.sgml.gz

Format: postscript
Files: /usr/share/doc/jlib/jlib.ps.gz

Format: text
Files: /usr/share/doc/jlib/jlib.text.gz

Format: HTML
Index: /usr/share/doc/jlib/html/index.html
Files: /usr/share/doc/jlib/html/*.html
