#!/usr/bin/env python3
"""Turn llama.cpp logit dumps into tests/reference_logits.hh.

Reads the raw float32 dumps written by dump_logits.cpp and emits a compact
fixture: the prompt ids, the reference's top-K token ids and logits, and a
strided sample of the whole vocabulary.

The full logit vector is 32k-256k floats per model, which is too large to
carry in the tree for three architectures.  What is kept is chosen to answer
the two questions the test asks -- does the distribution agree (the strided
sample bounds the maximum difference across the whole vocabulary) and does
the ranking agree (the top-K ids as a set).
"""

import sys, struct
from array import array

K, NS = 64, 256

HEAD = '''/* -*- mode: C++ c-basic-offset: 4  -*-
 *
 * Copyright (c) 2026 Joey Yandle <xoloki@gmail.com>
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * SPDX-License-Identifier: Apache-2.0
 *
 */

#ifndef JLIB_TESTS_REFERENCE_LOGITS_HH
#define JLIB_TESTS_REFERENCE_LOGITS_HH

#include <cstddef>

/**
 * Logits from llama.cpp, for the forward pass (#184).
 *
 * **Not produced by this code.**  Generated by `tools/reflogits`, which loads
 * the *same GGUF file* with llama.cpp and dumps the logits for the final
 * position of one forward pass.  Reading the same file matters: #180 found
 * that `modeling_gemma2.py` describes the HuggingFace checkpoint and the GGUF
 * is a different artefact, so an oracle built from HF weights would carry the
 * error it is meant to catch.
 *
 * llama.cpp commit: %(commit)s
 * Dumped on CPU (`-ngl 0`), because a reference wants to be reproducible
 * before it wants to be fast.
 *
 * Recorded rather than computed at test time, which is the same choice
 * `llama3_tokens.hh` makes and for a stronger reason here: llama.cpp changes
 * its own kernels, so a live binary would make this test's meaning drift with
 * somebody else's release schedule.  The commit is above so the fixture can
 * be regenerated and disagreements attributed.
 *
 * **The ids are the input, not the text.**  jlib's tokenizer is verified
 * against the same vendor files separately, so feeding ids keeps tokenization
 * out of a comparison that is about arithmetic.  The prompt text is recorded
 * only so a reader knows what was asked.
 */
struct reference_logits {
    const char*  model;        ///< the GGUF this was dumped from
    const char*  prompt;       ///< what the ids spell, for the reader
    int          ids[16];      ///< the forward pass input
    int          id_count;
    int          vocab;        ///< so a mismatched file is caught, not compared
    int          top_id[%(K)d];    ///< the reference's most likely tokens, in order
    float        top_logit[%(K)d]; ///< and their logits
    int          stride;       ///< sample[j] is the logit of token j*stride
    float        sample[%(NS)d];
};

'''

def load(p):
    a = array('f'); a.frombytes(open(p,'rb').read()); return list(a)

def one(name, model, prompt, ids, binpath):
    v = load(binpath)
    n = len(v)
    stride = max(1, n // NS)
    idx = list(range(0, n, stride))[:NS]
    top = sorted(range(n), key=lambda i: -v[i])[:K]

    out = []
    out.append(f"static const reference_logits {name} = {{")
    out.append(f'    "{model}",')
    out.append(f'    "{prompt}",')
    out.append("    { " + ", ".join(str(i) for i in ids) + " },")
    out.append(f"    {len(ids)},")
    out.append(f"    {n},")
    out.append("    {")
    for i in range(0, K, 8):
        out.append("        " + ", ".join(f"{t:6d}" for t in top[i:i+8]) + ",")
    out.append("    },")
    out.append("    {")
    for i in range(0, K, 6):
        out.append("        " + ", ".join(f"{v[t]:11.6f}f" for t in top[i:i+6]) + ",")
    out.append("    },")
    out.append(f"    {stride},")
    out.append("    {")
    for i in range(0, len(idx), 6):
        out.append("        " + ", ".join(f"{v[j]:11.6f}f" for j in idx[i:i+6]) + ",")
    out.append("    },")
    out.append("};")
    return "\n".join(out)

if __name__ == "__main__":
    commit = sys.argv[1]
    specs = [
        # name, model, prompt, ids, dump
        ("REF_LLAMA",  "tinyllama-1.1b-chat-v1.0.Q8_0.gguf", "The capital of France is",
         [1,450,7483,310,3444,338], sys.argv[2]),
        ("REF_QWEN2",  "qwen2.5-0.5b-instruct-q8_0.gguf", "The capital of France is",
         [785,6722,315,9625,374], sys.argv[3]),
        ("REF_GEMMA2", "gemma-2-2b-it-Q8_0.gguf", "The capital of France is",
         [2,651,6037,576,6081,603], sys.argv[4]),
    ]
    print(HEAD % {"commit": commit, "K": K, "NS": NS})
    for s in specs:
        print(one(*s))
        print()
    print("#endif // JLIB_TESTS_REFERENCE_LOGITS_HH")
