/* -*- mode: C++ c-basic-offset: 4  -*-
 *
 * Copyright (c) 2000 Joe Yandle <jwy@divisionbyzero.com>
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
 *
 */

#ifndef JLIB_MEDIA_WAVETABLE_HH
#define JLIB_MEDIA_WAVETABLE_HH

#include <jlib/media/Type.hh>
#include <jlib/media/instrument.hh>

#include <cmath>
#include <map>
#include <memory>
#include <mutex>
#include <vector>

namespace jlib {
namespace media {

/**
 * One cycle of a band-limited waveform, to read instead of computing.
 *
 * Summing harmonics is exact and cannot alias, and it is far too slow to do
 * live: measured, sixty-four voices at 110Hz take 122% of a core, and a D=10
 * hypercube has 1024 vertices.  The same sum done once into a table, then read
 * with interpolation, is about a thousand times cheaper -- 1024 voices come to
 * 1.2% of a core, and 16384 to 12.5%.
 *
 * It is the same sum, so the band limiting is identical.  What a table adds is
 * two approximations, both measured and both chosen to be small:
 *
 * **Interpolation.**  Reading between entries is not exact.  Measured against
 * the direct sum, a 4096-entry table read cubically is 117dB down -- below the
 * noise floor of 16-bit audio, at 16K per table.
 *
 * **Banding.**  A table has one harmonic count, so it can serve a range of
 * pitches only by being band-limited for the top of that range; a note at the
 * bottom is duller than it could be.  Measured at one table per octave that is
 * 19-34dB down and all of it in the top octave of the spectrum, where it reads
 * as slightly less air rather than as anything wrong.  DIVISIONS narrows the
 * range each table serves.
 *
 * Neither is aliasing, which is the point.  Aliasing puts energy at frequencies
 * unrelated to the note and is audibly wrong at any level; these either sit on
 * real harmonics or take a little off the top of them.
 *
 * For an exact result -- an offline render, where the cost does not matter --
 * do not use a table.  voice::quality selects.
 */
class wavetable {
public:
    /** Entries in a cycle.  See the interpolation figures above. */
    static const unsigned int SIZE = 4096;

    wavetable(instrument::wave w, unsigned int partials, unsigned int size = SIZE)
        : m_v(size + 1)
    {
        for(unsigned int i = 0; i < size; i++)
            m_v[i] = static_cast<Type::scaled>(
                shape(w, double(i) / size, partials));

        // One past the end, holding the wrap, so reading needs no branch.
        m_v[size] = m_v[0];
    }

    /**
     * The waveform at a phase in [0,1), by Catmull-Rom.
     *
     * Cubic rather than linear because it is most of two orders of magnitude
     * for four multiply-adds: at 4096 entries, linear is 80dB down and this is
     * 117dB.
     */
    Type::scaled at(double phase) const
    {
        const int n = static_cast<int>(m_v.size()) - 1;
        const double x = phase * n;
        const int i = static_cast<int>(x);
        const double f = x - i;

        const double p0 = m_v[(i - 1 + n) % n];
        const double p1 = m_v[i % n];
        const double p2 = m_v[(i + 1) % n];
        const double p3 = m_v[(i + 2) % n];

        return static_cast<Type::scaled>(
            p1 + 0.5 * f * (p2 - p0 +
                 f * (2*p0 - 5*p1 + 4*p2 - p3 +
                 f * (3*(p1 - p2) + p3 - p0))));
    }

    /**
     * The waveform, summed.  Shared with voice, which uses it directly when
     * asked for an exact result -- so a table cannot drift from the thing it
     * is a cache of.
     */
    static double shape(instrument::wave w, double phase, unsigned int partials);

protected:
    std::vector<Type::scaled> m_v;
};

/**
 * Tables for a whole instrument, built as they are asked for.
 *
 * Building every table up front is too slow to do at startup -- at a quarter
 * octave that is a second or so of summing -- and most of them would never be
 * used, since music occupies a few octaves rather than all of them.  So they
 * are built on first use and kept.
 *
 * That first build allocates and takes milliseconds, which must not happen on a
 * realtime thread.  In this library it does not: audio is generated by the
 * feeder thread and the device callback only drains a ring.  Anything that does
 * generate under a deadline should call prime() first.
 */
class wavetable_set {
public:
    /**
     * Tables per octave.
     *
     * Four keeps the worst-case pitch ratio within a table at 1.19, so a note
     * at the bottom of a band keeps 84% of its harmonics.  One per octave
     * halves them, which is the 19-34dB figure above.
     */
    static const unsigned int DIVISIONS = 4;

    /** The lowest pitch that gets its own band; below this they share. */
    static constexpr double BASE = 16.35;   // C0

    const wavetable& get(instrument::wave w, double freq, double rate)
    {
        const int band = band_of(freq);
        const key k{w, band};

        std::lock_guard<std::mutex> lock(m_lock);

        auto i = m_tables.find(k);
        if(i != m_tables.end())
            return *i->second;

        // Band-limited for the top of the band it serves, which is what makes
        // it safe for every pitch in the band rather than only the one it was
        // built for.
        const double top = BASE * std::pow(2.0, double(band + 1) / DIVISIONS);
        unsigned int partials = static_cast<unsigned int>(rate / 2 / top);
        if(partials < 1) partials = 1;

        auto t = std::unique_ptr<wavetable>(new wavetable(w, partials));
        const wavetable& ref = *t;
        m_tables[k] = std::move(t);

        return ref;
    }

    /** Build everything a pitch range will need, off the realtime path. */
    void prime(instrument::wave w, double low, double high, double rate)
    {
        for(int b = band_of(low); b <= band_of(high); b++)
            get(w, BASE * std::pow(2.0, (double(b) + 0.5) / DIVISIONS), rate);
    }

    std::size_t size() const
    {
        std::lock_guard<std::mutex> lock(m_lock);
        return m_tables.size();
    }

protected:
    static int band_of(double freq)
    {
        if(freq <= BASE)
            return 0;

        return static_cast<int>(std::floor(std::log2(freq / BASE) * DIVISIONS));
    }

    struct key {
        instrument::wave w;
        int band;

        bool operator<(const key& o) const
        {
            if(w != o.w) return w < o.w;
            return band < o.band;
        }
    };

    mutable std::mutex m_lock;
    std::map<key, std::unique_ptr<wavetable> > m_tables;
};

/**
 * The waveforms, as their Fourier series truncated at `partials`.
 *
 * Each is scaled so all four have the RMS of a unit sine.  Matching peaks
 * instead would make changing waveform change level by 3dB -- that is how much
 * louder a square is than a sine at the same peak -- so the peaks differ
 * instead: a sawtooth reaches about 1.22 before gain, plus the ~9% a truncated
 * series overshoots by at the discontinuity.
 *
 * What this does not do is make them equally *loud*, and it is worth being
 * exact about that, because matching RMS looks like it should.  The ear sums
 * loudness across critical bands, so the same energy spread over many bands is
 * louder than the same energy in one -- and that is the entire difference
 * between these waveforms.  Measured on a C major triad, limiter engaged:
 *
 *     sine      3 partials in  3 bands   energy -10.7dB   loudness 1.33
 *     triangle  103        in 18 bands          -11.7dB            2.32
 *     saw       103        in 18 bands          -12.1dB            4.32
 *     square    103        in 18 bands           -9.7dB            3.96
 *
 * A sawtooth carries 1.4dB *less* energy than a sine here and sounds markedly
 * louder.  So equal RMS is the right thing to hold -- it is at least a property
 * of the signal rather than of the listener -- but the fader still has work to
 * do when the waveform changes, and no scaling here can do it instead.
 */
inline double wavetable::shape(instrument::wave w, double phase,
                               unsigned int partials)
{
    if(partials == 0)
        return 0;

    static const double pi = 3.14159265358979323846;
    static const double SAW_RMS      = 1.2247448713915890;   // sqrt(3/2)
    static const double SQUARE_RMS   = 0.7071067811865476;   // 1/sqrt(2)
    static const double TRIANGLE_RMS = 1.2247448713915890;

    const double w2 = 2 * pi * phase;

    switch(w) {
    case instrument::wave::sine:
        return std::sin(w2);

    case instrument::wave::saw: {
        double sum = 0;
        for(unsigned int k = 1; k <= partials; k++)
            sum += ((k % 2) ? 1.0 : -1.0) * std::sin(k * w2) / k;

        return SAW_RMS * (2.0 / pi) * sum;
    }

    case instrument::wave::square: {
        double sum = 0;
        for(unsigned int k = 1; k <= partials; k += 2)
            sum += std::sin(k * w2) / k;

        return SQUARE_RMS * (4.0 / pi) * sum;
    }

    case instrument::wave::triangle: {
        double sum = 0;
        for(unsigned int k = 1; k <= partials; k += 2) {
            const double sign = (((k - 1) / 2) % 2) ? -1.0 : 1.0;
            sum += sign * std::sin(k * w2) / (double(k) * k);
        }

        return TRIANGLE_RMS * (8.0 / (pi * pi)) * sum;
    }
    }

    return 0;
}

}
}

#endif // JLIB_MEDIA_WAVETABLE_HH
